### ISSUE TITLE
I cannot install the extension

### ISSUE THREAD

**Issue by ghost** [scottharwell/OciFnAuth#7]
I am using the Trial version (if that is important). I am installing it from Paw 3.3.1 using Paw -> Extensions -> Install Extension by Identifier and I am using me.harwell.PawExtensions.OciFnAuth as identifier. The installer apparently runs but at the end it's not installed, nor is it listed in the list of installed extensions.

**Comment by ghost** [comment]
In the console I can see:
Error Cannot find main JavaScript file (OciFnAuth.js) for extension me.harwell.PawExtensions.OciFnAuth

**Comment by scottharwell** [comment]
This sounds more like a Paw issue than an extension issue.  When you click the button `Open Directory`, what files do you see in the `me.harwell.PawExtensions.OciFnAuth` folder?
